# Generated by Django 6.0.2 on 2026-02-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional if flat page.', max_length=200, verbose_name='title')),
                ('url', models.URLField(blank=True, help_text='Leave blank if flat page.', max_length=1000, verbose_name='URL')),
                ('priority', models.IntegerField(default=1000, help_text='Priority of display in the menu.Lower values are displayed first.', verbose_name='priority')),
                ('flatpage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_item', to='flatpages.flatpage', verbose_name='flat page')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['priority', 'title'],
            },
        ),
    ]
