# Generated by Django 6.0.2 on 2026-02-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority of display in the menu. Lower values are displayed first. 0 is not displayed.', verbose_name='priority'),
        ),
    ]
