# Generated by Django 6.0.2 on 2026-02-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdf', '0002_alter_menuitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, help_text='Description for meta tags.', max_length=1000, verbose_name='description'),
        ),
    ]
