# Generated by Django 6.0.2 on 2026-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdf', '0003_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image for meta tags. Relative path if in static files, or full URL.', max_length=2048, verbose_name='image URL'),
        ),
    ]
